---

- name: "install tmux"
  community.general.homebrew:
    name: tmux
  tags: homebrew

- name: "install tpm"
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_user_dir }}/.tmux/plugins/tpm"
    version: master

- name: "install tmux plugins"
  ansible.builtin.command:
    cmd: "{{ ansible_user_dir }}/.tmux/plugins/tpm/bin/install_plugins"
  register: task
  changed_when: '"download success" in task.stdout'
