---

- block:

  - name: "install fonts"
    community.general.homebrew_cask:
      name:
        - font-powerline-symbols
        - font-fira-code-nerd-font
      install_options: no-quarantine
      accept_external_apps: true

  tags:
    - font_install
    - homebrew
